
-- START UNDO OF CHANGE SCRIPT #104: 104_update-foo-table.sql

START TRANSACTION;

DROP TABLE FOO;


DELETE FROM CHANGELOG WHERE change_number = 104;

COMMIT;

-- END UNDO OF CHANGE SCRIPT #104: 104_update-foo-table.sql


-- START UNDO OF CHANGE SCRIPT #103: 103_alter-foo-add-column.sql

START TRANSACTION;

ALTER TABLE FOO DROP COLUMN FOO_AGE;


DELETE FROM CHANGELOG WHERE change_number = 103;

COMMIT;

-- END UNDO OF CHANGE SCRIPT #103: 103_alter-foo-add-column.sql


-- START UNDO OF CHANGE SCRIPT #102: 102_alter-foo-table.sql

START TRANSACTION;

ALTER TABLE FOO DROP COLUMN FOO_DATE;




DELETE FROM CHANGELOG WHERE change_number = 102;

COMMIT;

-- END UNDO OF CHANGE SCRIPT #102: 102_alter-foo-table.sql

